//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.dns.android.authoritative.activities;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.text.Editable;
import android.text.TextWatcher;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.dns.android.authoritative.R.id;
import com.dns.android.authoritative.R.layout;
import com.dns.android.authoritative.rest.RestClient_;
import com.dns.android.authoritative.utils.DNSPrefs_;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class SettingsActivity_
    extends SettingsActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.settings_layout);
    }

    private void init_(Bundle savedInstanceState) {
        prefs = new DNSPrefs_(this);
        client = RestClient_.getInstance_(this);
    }

    private void afterSetContentView_() {
        loadingAuthTokenIndicator = ((ProgressBar) findViewById(id.loadingAuthTokenIndicator));
        getTokenButton = ((Button) findViewById(id.tokenRetrieveButton));
        webAppURL = ((EditText) findViewById(id.appUrlInput));
        tokenInput = ((EditText) findViewById(id.tokenInput));
        {
            View view = findViewById(id.tokenRetrieveButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SettingsActivity_.this.showAuthTokenDialog();
                    }

                }
                );
            }
        }
        ((RestClient_) client).afterSetContentView_();
        {
            final TextView view = ((TextView) findViewById(id.tokenInput));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void afterTextChanged(Editable s) {
                        SettingsActivity_.this.saveChangedAuthToken();
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                    }

                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) findViewById(id.appUrlInput));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void afterTextChanged(Editable s) {
                        SettingsActivity_.this.saveChangedAppURL();
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                    }

                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                }
                );
            }
        }
        configureListeners();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static SettingsActivity_.IntentBuilder_ intent(Context context) {
        return new SettingsActivity_.IntentBuilder_(context);
    }

    @Override
    public void authTokenFailure() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SettingsActivity_.super.authTokenFailure();
                } catch (RuntimeException e) {
                    Log.e("SettingsActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void authTokenSuccess() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SettingsActivity_.super.authTokenSuccess();
                } catch (RuntimeException e) {
                    Log.e("SettingsActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void getAuthToken(final String username, final String password) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    SettingsActivity_.super.getAuthToken(username, password);
                } catch (RuntimeException e) {
                    Log.e("SettingsActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SettingsActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SettingsActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
