//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.dns.android.authoritative.utils;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class DNSPrefs_
    extends SharedPreferencesHelper
{


    public DNSPrefs_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
    }

    public DNSPrefs_.DNSPrefsEditor_ edit() {
        return new DNSPrefs_.DNSPrefsEditor_(getSharedPreferences());
    }

    public StringPrefField getAuthToken() {
        return stringField("getAuthToken", "");
    }

    public StringPrefField getBaseAddress() {
        return stringField("getBaseAddress", "http://home.zanclus.com:7080/rest/v2");
    }

    public final static class DNSPrefsEditor_
        extends EditorHelper<DNSPrefs_.DNSPrefsEditor_>
    {


        DNSPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<DNSPrefs_.DNSPrefsEditor_> getAuthToken() {
            return stringField("getAuthToken");
        }

        public StringPrefEditorField<DNSPrefs_.DNSPrefsEditor_> getBaseAddress() {
            return stringField("getBaseAddress");
        }

    }

}
