//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.dns.android.authoritative.fragments;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.dns.android.authoritative.R.layout;
import com.dns.android.authoritative.utils.DNSPrefs_;

public final class GeoGroupsFragment_
    extends GeoGroupsFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        prefs = new DNSPrefs_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.geo_groups_fragment, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static GeoGroupsFragment_.FragmentBuilder_ builder() {
        return new GeoGroupsFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public GeoGroupsFragment build() {
            GeoGroupsFragment_ fragment_ = new GeoGroupsFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
