//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.dns.android.authoritative.fragments;

import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.AdapterView.OnItemLongClickListener;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.dns.android.authoritative.R.layout;
import com.dns.android.authoritative.domain.Host;
import com.dns.android.authoritative.rest.RestClient_;
import com.dns.android.authoritative.utils.DNSPrefs_;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class HostsFragment_
    extends HostsFragment
{

    private View contentView_;
    private Handler handler_ = new Handler();

    private void init_(Bundle savedInstanceState) {
        prefs = new DNSPrefs_(getActivity());
        client = RestClient_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        hostsLoadingIndicator = ((ProgressBar) findViewById(com.dns.android.authoritative.R.id.hostListBusyIndicator));
        hostsListView = ((ListView) findViewById(com.dns.android.authoritative.R.id.hostListView));
        hostsFragmentLabel = ((TextView) findViewById(com.dns.android.authoritative.R.id.hostsFragmentLabel));
        hostFilter = ((EditText) findViewById(com.dns.android.authoritative.R.id.hostFilter));
        {
            View view = findViewById(com.dns.android.authoritative.R.id.hostFilterApply);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HostsFragment_.this.onSearchApply();
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(com.dns.android.authoritative.R.id.hostListView));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        handleHostClick(((Host) parent.getAdapter().getItem(position)));
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(com.dns.android.authoritative.R.id.hostListView));
            if (view!= null) {
                view.setOnItemLongClickListener(new OnItemLongClickListener() {


                    @Override
                    public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                        handleHostLongClicked(((Host) parent.getAdapter().getItem(position)));
                        return true;
                    }

                }
                );
            }
        }
        ((RestClient_) client).afterSetContentView_();
        setupUi();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.hosts_fragment, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static HostsFragment_.FragmentBuilder_ builder() {
        return new HostsFragment_.FragmentBuilder_();
    }

    @Override
    public void hostDeleteFailed(final Host host) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    HostsFragment_.super.hostDeleteFailed(host);
                } catch (RuntimeException e) {
                    Log.e("HostsFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void setListViewAdapter() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    HostsFragment_.super.setListViewAdapter();
                } catch (RuntimeException e) {
                    Log.e("HostsFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void hostDeleteSuceeded(final Host host) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    HostsFragment_.super.hostDeleteSuceeded(host);
                } catch (RuntimeException e) {
                    Log.e("HostsFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void updateListAdapter() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    HostsFragment_.super.updateListAdapter();
                } catch (RuntimeException e) {
                    Log.e("HostsFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void loadInitialHosts() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    HostsFragment_.super.loadInitialHosts();
                } catch (RuntimeException e) {
                    Log.e("HostsFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void loadFilteredHosts() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    HostsFragment_.super.loadFilteredHosts();
                } catch (RuntimeException e) {
                    Log.e("HostsFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void deleteHost(final Host host) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    HostsFragment_.super.deleteHost(host);
                } catch (RuntimeException e) {
                    Log.e("HostsFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public HostsFragment build() {
            HostsFragment_ fragment_ = new HostsFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
