//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.dns.android.authoritative.fragments;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.dns.android.authoritative.R.layout;
import com.dns.android.authoritative.rest.RestClient_;
import com.dns.android.authoritative.utils.DNSPrefs_;

public final class RRListFragment_
    extends RRListFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        prefs = new DNSPrefs_(getActivity());
        client = RestClient_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        rrsListView = ((ListView) findViewById(com.dns.android.authoritative.R.id.rrListView));
        rrsLoadingIndicator = ((ProgressBar) findViewById(com.dns.android.authoritative.R.id.rrListBusyIndicator));
        rrFilter = ((EditText) findViewById(com.dns.android.authoritative.R.id.rrFilter));
        rrsFragmentLabel = ((TextView) findViewById(com.dns.android.authoritative.R.id.rrsFragmentLabel));
        ((RestClient_) client).afterSetContentView_();
        setupUi();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.rr_list_fragment, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static RRListFragment_.FragmentBuilder_ builder() {
        return new RRListFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public RRListFragment build() {
            RRListFragment_ fragment_ = new RRListFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
